# Arkham Data Science Challenge

## Task 1: Data extraction

In [18]:
import requests as rq
import pandas as pd
import openpyxl
import time
from datetime import date, timedelta

In [4]:
nodos = pd.read_excel('catalogonodos.xlsx', header = 1)
nodos.columns

Index(['SISTEMA', 'CENTRO DE CONTROL REGIONAL', 'ZONA DE CARGA', 'CLAVE',
       'NOMBRE', 'NIVEL DE TENSIÓN (kV)', 'DIRECTAMENTE MODELADA',
       'INDIRECTAMENTE MODELADA', 'DIRECTAMENTE MODELADA.1',
       'INDIRECTAMENTE MODELADA.1', 'ZONA DE OPERACIÓN DE TRANSMISIÓN',
       'GERENCIA REGIONAL DE TRANSMISIÓN', 'ZONA DE DISTRIBUCIÓN',
       'GERENCIA DIVISIONAL DE DISTRIBUCIÓN',
       'CLAVE DE ENTIDAD FEDERATIVA (INEGI)', 'ENTIDAD FEDERATIVA (INEGI)',
       'CLAVE DE MUNICIPIO (INEGI)', 'MUNICIPIO (INEGI)',
       'REGION DE TRANSMISION'],
      dtype='str')

In [5]:
len(nodos)

2585

In [6]:
#True if ('Monclova' in nodos['ZONA DE CARGA'].unique()) else False
nodos['ZONA DE CARGA'].unique()

<StringArray>
[      'ENSENADA',       'MEXICALI',        'SANLUIS',        'TIJUANA',
      'No Aplica',   'CONSTITUCION',         'LA PAZ',      'LOS CABOS',
 'CENTRO ORIENTE',     'CENTRO SUR',
 ...
         'XALAPA',    'ZIHUATANEJO',       'CAMPECHE',         'CANCUN',
         'CARMEN',       'CHETUMAL',         'MERIDA',  'MOTUL TIZIMIN',
   'RIVIERA MAYA',          'TICUL']
Length: 109, dtype: str

In [7]:
nodos_mclv = nodos[nodos['ZONA DE CARGA'].str.lower() == 'monclova']
nodos_mclv_str = ','.join(nodos_mclv['CLAVE'])
nodos_mclv_str

'06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115'

In [ ]:
sistema = 'SIN'
proceso = 'MDA'
lista_nodos = nodos_mclv_str
anio_ini = '2024'
mes_ini = '01'
dia_ini = '01'
anio_fin = '2024'
mes_fin = '01'
dia_fin = '02'
formato = 'JSON'

url = f'https://ws01.cenace.gob.mx:8082/SWPML/SIM/{sistema}/{proceso}/{lista_nodos}/{anio_ini}/{mes_ini}/{dia_ini}/{anio_fin}/{mes_fin}/{dia_fin}/{formato}'
respuesta = rq.get(url)

if respuesta.status_code == 200:
    
    # 3. Conviertes la respuesta directamente a un diccionario de Python
    datos_json = respuesta.json()
    
    # Aquí ya puedes acceder a datos_json['Resultados'] y procesarlos
    print(f"DAtos para el request a {url}")
    # 1. Load the in-memory JSON data directly
    df = pd.DataFrame(datos_json)

    # Save as CSV
    #df.to_csv("resultado.csv", index=False)
    df = df['Resultados']
    print(df)
else:
    print(f"Ups, error en el servidor: {respuesta.status_code}")

# 4. Haces una pequeña pausa antes de la siguiente vuelta del bucle
time.sleep(2)

DAtos para el request a https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/01/01/2024/01/02/JSON
0    {'clv_nodo': '06AEO-115', 'Valores': [{'fecha'...
1    {'clv_nodo': '06AHM-400', 'Valores': [{'fecha'...
2    {'clv_nodo': '06FRO-115', 'Valores': [{'fecha'...
3    {'clv_nodo': '06GRA-115', 'Valores': [{'fecha'...
4    {'clv_nodo': '06MON-115', 'Valores': [{'fecha'...
5    {'clv_nodo': '06MON-230', 'Valores': [{'fecha'...
6    {'clv_nodo': '06RGS-115', 'Valores': [{'fecha'...
7    {'clv_nodo': '06TKS-115', 'Valores': [{'fecha'...
8    {'clv_nodo': '06XOC-115', 'Valores': [{'fecha'...
Name: Resultados, dtype: object

In [ ]:
def flattenData(form):
    flattenedRows = []
    for nodo in form['Resultados']:
        clave = nodo['clv_nodo']
        for valores in nodo['Valores']:
            valores['nodo'] = clave 
            flattenedRows.append(valores)

    return pd.DataFrame(flattenedRows)

In [10]:
flattenData(datos_json)

          fecha hora     pml pml_ene pml_per pml_cng       nodo
0    2024-01-01    1  279.92  370.71  -43.69   -47.1  06AEO-115
1    2024-01-01    2  279.21  311.75  -32.54       0  06AEO-115
2    2024-01-01    3  274.23  305.52  -31.28       0  06AEO-115
3    2024-01-01    4  264.01  294.23  -30.22       0  06AEO-115
4    2024-01-01    5  243.44  267.66  -24.22       0  06AEO-115
..          ...  ...     ...     ...     ...     ...        ...
427  2024-01-02   20  594.32  649.19  -54.86       0  06XOC-115
428  2024-01-02   21  392.26  431.03  -38.77       0  06XOC-115
429  2024-01-02   22  592.27  646.27  -52.38   -1.62  06XOC-115
430  2024-01-02   23  490.33  535.61  -45.28       0  06XOC-115
431  2024-01-02   24  353.77  385.85  -32.08       0  06XOC-115

[432 rows x 7 columns]

In [19]:
def getRequestURLs(startDate, endDate, lista_nodos, sistema='SIN', proceso='MDA', formato='JSON'):
    URLlist = []
    current_date = startDate
    
    while current_date <= endDate: 
    
        chunk_end = current_date + timedelta(days=6)
        if chunk_end > endDate:
            chunk_end = endDate

        # .strftime("%Y/%m/%d") asegura el formato exacto que pide el CENACE
        f_ini = current_date.strftime("%Y/%m/%d")
        f_fin = chunk_end.strftime("%Y/%m/%d")
        
        url = f"https://ws01.cenace.gob.mx:8082/SWPML/SIM/{sistema}/{proceso}/{lista_nodos}/{f_ini}/{f_fin}/{formato}"

        URLlist.append(url)

        current_date = chunk_end + timedelta(days=1)
        
    return URLlist

In [23]:
urlList = getRequestURLs(date(2024,1,1), date(2025,6,30), nodos_mclv_str)
urlList

['https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/01/01/2024/01/07/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/01/08/2024/01/14/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/01/15/2024/01/21/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/01/22/2024/01/28/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/01/29/2024/02/04/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/02/05/2024/02/11/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/02/12/2024/02/18/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/02/19/2024/02/25/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/02/26/2024/03/03/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/03/04/2024/03/10/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/03/11/2024/03/17/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/03/18/2024/03/24/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/03/25/2024/03/31/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/04/01/2024/04/07/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/04/08/2024/04/14/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/04/15/2024/04/21/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/04/22/2024/04/28/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/04/29/2024/05/05/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/05/06/2024/05/12/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/05/13/2024/05/19/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/05/20/2024/05/26/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/05/27/2024/06/02/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/06/03/2024/06/09/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/06/10/2024/06/16/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/06/17/2024/06/23/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/06/24/2024/06/30/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/07/01/2024/07/07/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/07/08/2024/07/14/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/07/15/2024/07/21/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/07/22/2024/07/28/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/07/29/2024/08/04/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/08/05/2024/08/11/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/08/12/2024/08/18/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/08/19/2024/08/25/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/08/26/2024/09/01/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/09/02/2024/09/08/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/09/09/2024/09/15/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/09/16/2024/09/22/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/09/23/2024/09/29/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/09/30/2024/10/06/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/10/07/2024/10/13/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/10/14/2024/10/20/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/10/21/2024/10/27/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/10/28/2024/11/03/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/11/04/2024/11/10/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/11/11/2024/11/17/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/11/18/2024/11/24/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/11/25/2024/12/01/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/12/02/2024/12/08/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/12/09/2024/12/15/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/12/16/2024/12/22/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/12/23/2024/12/29/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2024/12/30/2025/01/05/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/01/06/2025/01/12/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/01/13/2025/01/19/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/01/20/2025/01/26/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/01/27/2025/02/02/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/02/03/2025/02/09/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/02/10/2025/02/16/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/02/17/2025/02/23/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/02/24/2025/03/02/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/03/03/2025/03/09/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/03/10/2025/03/16/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/03/17/2025/03/23/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/03/24/2025/03/30/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/03/31/2025/04/06/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/04/07/2025/04/13/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/04/14/2025/04/20/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/04/21/2025/04/27/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/04/28/2025/05/04/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/05/05/2025/05/11/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/05/12/2025/05/18/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/05/19/2025/05/25/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/05/26/2025/06/01/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/06/02/2025/06/08/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/06/09/2025/06/15/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/06/16/2025/06/22/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/06/23/2025/06/29/JSON',
 'https://ws01.cenace.gob.mx:8082/SWPML/SIM/SIN/MDA/06AEO-115,06AHM-400,06FRO-115,06GRA-115,06MON-115,06MON-230,06RGS-115,06TKS-115,06XOC-115/2025/06/30/2025/06/30/JSON']

In [24]:
lista_chunks = []
for link in urlList:
    respuesta = rq.get(link)

    if respuesta.status_code == 200:
        rowsChunk = flattenData(respuesta.json())
        print(f"Datos para el request a {link[-30:]}")
        print(rowsChunk)
        lista_chunks.append(rowsChunk)
        
    else:
        print(f"Ups, error en el servidor: {respuesta.status_code}")

    time.sleep(2)

Datos para el request a 115/2024/01/01/2024/01/07/JSON
           fecha hora     pml pml_ene pml_per pml_cng       nodo
0     2024-01-01    1  279.92  370.71  -43.69   -47.1  06AEO-115
1     2024-01-01    2  279.21  311.75  -32.54       0  06AEO-115
2     2024-01-01    3  274.23  305.52  -31.28       0  06AEO-115
3     2024-01-01    4  264.01  294.23  -30.22       0  06AEO-115
4     2024-01-01    5  243.44  267.66  -24.22       0  06AEO-115
...          ...  ...     ...     ...     ...     ...        ...
1507  2024-01-07   20  483.26  603.07  -76.33  -43.48  06XOC-115
1508  2024-01-07   21  482.72  602.26   -75.5  -44.03  06XOC-115
1509  2024-01-07   22  458.49  581.47  -72.13  -50.85  06XOC-115
1510  2024-01-07   23  410.74  468.46  -57.72       0  06XOC-115
1511  2024-01-07   24  375.39  428.35  -52.95       0  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/01/08/2024/01/14/JSON
           fecha hora     pml  pml_ene  pml_per  pml_cng       nodo
0     2024-01-08    1  409.38   454.01   -44.63        0  06AEO-115
1     2024-01-08    2   381.9   426.37   -44.48        0  06AEO-115
2     2024-01-08    3  368.93   411.42   -42.48        0  06AEO-115
3     2024-01-08    4  345.82   385.41   -39.59        0  06AEO-115
4     2024-01-08    5  345.34   387.23   -41.89        0  06AEO-115
...          ...  ...     ...      ...      ...      ...        ...
1507  2024-01-14   20  500.21     1089   -132.2   -456.6  06XOC-115
1508  2024-01-14   21  477.24  1006.79  -126.47  -403.09  06XOC-115
1509  2024-01-14   22  504.38  1033.26  -129.44  -399.44  06XOC-115
1510  2024-01-14   23  473.16   993.44  -126.06  -394.21  06XOC-115
1511  2024-01-14   24  453.76   769.99  -100.92  -215.31  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/01/15/2024/01/21/JSON
           fecha hora      pml  pml_ene pml_per pml_cng       nodo
0     2024-01-15    1   430.34   492.71  -62.37       0  06AEO-115
1     2024-01-15    2   418.77   473.12  -54.35       0  06AEO-115
2     2024-01-15    3   415.94    465.5  -49.56       0  06AEO-115
3     2024-01-15    4   414.63   460.27  -45.64       0  06AEO-115
4     2024-01-15    5   419.41   466.43  -47.02       0  06AEO-115
...          ...  ...      ...      ...     ...     ...        ...
1507  2024-01-21   20  1020.25   1094.3  -74.04       0  06XOC-115
1508  2024-01-21   21  1049.77  1121.49  -71.72       0  06XOC-115
1509  2024-01-21   22  1032.89  1100.37  -67.48       0  06XOC-115
1510  2024-01-21   23   669.82   715.73   -45.9       0  06XOC-115
1511  2024-01-21   24   438.74    465.3   -26.4   -0.16  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/01/22/2024/01/28/JSON
           fecha hora     pml pml_ene pml_per  pml_cng       nodo
0     2024-01-22    1   442.3  465.45  -23.15        0  06AEO-115
1     2024-01-22    2  397.26  418.47  -21.21        0  06AEO-115
2     2024-01-22    3  383.42  403.92   -20.5        0  06AEO-115
3     2024-01-22    4  372.78  393.31  -20.53        0  06AEO-115
4     2024-01-22    5  371.76   393.4  -21.64        0  06AEO-115
...          ...  ...     ...     ...     ...      ...        ...
1507  2024-01-28   20  521.77  794.33  -70.49  -202.06  06XOC-115
1508  2024-01-28   21   520.1   784.1  -67.47  -196.53  06XOC-115
1509  2024-01-28   22  831.15  911.67  -80.52        0  06XOC-115
1510  2024-01-28   23  519.67  569.03  -49.36        0  06XOC-115
1511  2024-01-28   24  400.54  434.59  -34.05        0  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/01/29/2024/02/04/JSON
           fecha hora     pml pml_ene  pml_per  pml_cng       nodo
0     2024-01-29    1  391.99  422.61   -30.62        0  06AEO-115
1     2024-01-29    2  372.62   400.2   -27.58        0  06AEO-115
2     2024-01-29    3   355.2  380.58   -25.39        0  06AEO-115
3     2024-01-29    4  356.25  379.03   -22.78        0  06AEO-115
4     2024-01-29    5  361.39   383.3    -21.9        0  06AEO-115
...          ...  ...     ...     ...      ...      ...        ...
1507  2024-02-04   20  423.57  602.11   -71.82  -106.71  06XOC-115
1508  2024-02-04   21  726.22  990.83  -115.28  -149.33  06XOC-115
1509  2024-02-04   22  328.81  388.25   -46.24    -13.2  06XOC-115
1510  2024-02-04   23  364.46  421.19   -49.42    -7.31  06XOC-115
1511  2024-02-04   24  322.12  368.83   -41.81    -4.89  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/02/05/2024/02/11/JSON
           fecha hora     pml pml_ene pml_per pml_cng       nodo
0     2024-02-05    1  323.26  366.46  -38.19   -5.01  06AEO-115
1     2024-02-05    2  298.76   339.8  -37.02   -4.03  06AEO-115
2     2024-02-05    3  289.38  327.26  -34.38    -3.5  06AEO-115
3     2024-02-05    4   288.8   329.8  -37.19    -3.8  06AEO-115
4     2024-02-05    5  284.78  325.36  -36.49   -4.09  06AEO-115
...          ...  ...     ...     ...     ...     ...        ...
1507  2024-02-11   20  352.93  407.98  -48.14   -6.91  06XOC-115
1508  2024-02-11   21  485.94  562.98  -63.73   -13.3  06XOC-115
1509  2024-02-11   22  334.37  387.65  -46.87   -6.42  06XOC-115
1510  2024-02-11   23  610.87  717.83  -82.09  -24.87  06XOC-115
1511  2024-02-11   24   299.1  348.07  -43.64   -5.33  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/02/12/2024/02/18/JSON
           fecha hora     pml pml_ene pml_per pml_cng       nodo
0     2024-02-12    1  297.99  331.77  -29.01   -4.77  06AEO-115
1     2024-02-12    2  266.02  297.66  -28.35   -3.29  06AEO-115
2     2024-02-12    3  257.67  287.26  -26.67   -2.92  06AEO-115
3     2024-02-12    4  253.24   283.2  -27.09   -2.87  06AEO-115
4     2024-02-12    5  249.87  294.89  -22.22  -22.81  06AEO-115
...          ...  ...     ...     ...     ...     ...        ...
1507  2024-02-18   20  450.23  492.47  -26.12  -16.12  06XOC-115
1508  2024-02-18   21  487.76  535.39  -29.04  -18.59  06XOC-115
1509  2024-02-18   22  376.68  408.57  -20.54  -11.35  06XOC-115
1510  2024-02-18   23  322.14  349.96  -19.35   -8.47  06XOC-115
1511  2024-02-18   24  285.37  310.57  -18.83   -6.37  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/02/19/2024/02/25/JSON
           fecha hora     pml pml_ene pml_per pml_cng       nodo
0     2024-02-19    1  263.83  282.94   -13.9   -5.21  06AEO-115
1     2024-02-19    2  250.45  268.01  -13.19   -4.37  06AEO-115
2     2024-02-19    3  248.62   265.9  -13.13   -4.15  06AEO-115
3     2024-02-19    4  247.98  263.66   -11.7   -3.98  06AEO-115
4     2024-02-19    5  249.68  265.28  -11.43   -4.18  06AEO-115
...          ...  ...     ...     ...     ...     ...        ...
1507  2024-02-25   20  420.28  538.66  -70.34  -48.04  06XOC-115
1508  2024-02-25   21  289.79  401.69  -52.35  -59.55  06XOC-115
1509  2024-02-25   22  275.34  376.84  -49.41  -52.09  06XOC-115
1510  2024-02-25   23  266.61  348.33  -45.59  -36.14  06XOC-115
1511  2024-02-25   24  252.35  295.28   -37.1   -5.83  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/02/26/2024/03/03/JSON
           fecha hora     pml  pml_ene  pml_per  pml_cng       nodo
0     2024-02-26    1  252.19   292.27   -34.21    -5.87  06AEO-115
1     2024-02-26    2  228.12   261.97   -29.43    -4.42  06AEO-115
2     2024-02-26    3  217.15   247.41   -26.41    -3.86  06AEO-115
3     2024-02-26    4  214.99   243.69   -25.14    -3.56  06AEO-115
4     2024-02-26    5  218.35    247.3   -25.01    -3.94  06AEO-115
...          ...  ...     ...      ...      ...      ...        ...
1507  2024-03-03   20     596  1265.28  -164.03  -505.25  06XOC-115
1508  2024-03-03   21  580.48  1365.78  -179.21   -606.1  06XOC-115
1509  2024-03-03   22  491.52  1094.68  -145.34  -457.82  06XOC-115
1510  2024-03-03   23  475.14   733.54    -99.6   -158.8  06XOC-115
1511  2024-03-03   24  272.55   390.69   -53.66   -64.47  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/03/04/2024/03/10/JSON
           fecha hora     pml pml_ene pml_per pml_cng       nodo
0     2024-03-04    1  309.99  366.62  -41.61  -15.02  06AEO-115
1     2024-03-04    2  266.33  321.28  -40.29  -14.67  06AEO-115
2     2024-03-04    3  261.86  310.82  -36.65  -12.31  06AEO-115
3     2024-03-04    4  245.98   288.4  -32.19  -10.24  06AEO-115
4     2024-03-04    5  249.04   289.6  -31.04   -9.52  06AEO-115
...          ...  ...     ...     ...     ...     ...        ...
1507  2024-03-10   20  271.37  344.58  -43.87  -29.33  06XOC-115
1508  2024-03-10   21  282.78  362.98   -46.9   -33.3  06XOC-115
1509  2024-03-10   22  285.94  348.26  -43.48  -18.85  06XOC-115
1510  2024-03-10   23  282.07  343.49  -42.38  -19.04  06XOC-115
1511  2024-03-10   24  263.34  316.67   -37.4  -15.94  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/03/11/2024/03/17/JSON
           fecha hora     pml pml_ene pml_per  pml_cng       nodo
0     2024-03-11    1  269.67  294.84  -22.85    -2.32  06AEO-115
1     2024-03-11    2  257.98  282.38  -21.99    -2.41  06AEO-115
2     2024-03-11    3  254.71  276.64   -21.2    -0.73  06AEO-115
3     2024-03-11    4  253.46  274.75  -20.38    -0.91  06AEO-115
4     2024-03-11    5  253.15  274.81  -19.96     -1.7  06AEO-115
...          ...  ...     ...     ...     ...      ...        ...
1507  2024-03-17   20   532.3  825.22  -70.97  -221.95  06XOC-115
1508  2024-03-17   21  671.85  931.05  -81.46  -177.75  06XOC-115
1509  2024-03-17   22  727.34  827.47  -70.43    -29.7  06XOC-115
1510  2024-03-17   23  573.51  715.13  -66.01   -75.61  06XOC-115
1511  2024-03-17   24  464.23  476.45  -40.34    28.12  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/03/18/2024/03/24/JSON
           fecha hora     pml pml_ene  pml_per pml_cng       nodo
0     2024-03-18    1  294.62   319.4   -23.47   -1.31  06AEO-115
1     2024-03-18    2  268.12  292.47   -23.41   -0.94  06AEO-115
2     2024-03-18    3   254.8  280.63   -24.31   -1.52  06AEO-115
3     2024-03-18    4  252.06  280.95      -27   -1.89  06AEO-115
4     2024-03-18    5   244.3  275.62   -27.87   -3.45  06AEO-115
...          ...  ...     ...     ...      ...     ...        ...
1507  2024-03-24   20   505.2  628.91    -82.6  -41.11  06XOC-115
1508  2024-03-24   21  347.25  421.83   -55.23  -19.35  06XOC-115
1509  2024-03-24   22  703.34  879.04  -113.62  -62.08  06XOC-115
1510  2024-03-24   23  361.47  439.19   -56.27  -21.45  06XOC-115
1511  2024-03-24   24   273.9  329.51   -40.18  -15.43  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/03/25/2024/03/31/JSON
           fecha hora     pml pml_ene pml_per  pml_cng       nodo
0     2024-03-25    1  266.58  296.97  -28.11    -2.28  06AEO-115
1     2024-03-25    2  245.72  272.45  -24.96    -1.76  06AEO-115
2     2024-03-25    3  242.57  269.58  -23.81     -3.2  06AEO-115
3     2024-03-25    4  237.05  263.39  -23.05    -3.29  06AEO-115
4     2024-03-25    5  240.22  263.91  -20.57    -3.12  06AEO-115
...          ...  ...     ...     ...     ...      ...        ...
1507  2024-03-31   20  272.67  478.57  -56.23  -149.68  06XOC-115
1508  2024-03-31   21  246.08  367.08  -44.29   -76.71  06XOC-115
1509  2024-03-31   22   288.4  402.48  -47.52   -66.56  06XOC-115
1510  2024-03-31   23  262.63  360.11  -42.95   -54.53  06XOC-115
1511  2024-03-31   24  294.45  344.66   -41.5    -8.71  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/04/01/2024/04/07/JSON
           fecha hora     pml pml_ene pml_per  pml_cng       nodo
0     2024-04-01    1  246.13  547.11  -61.55  -239.43  06AEO-115
1     2024-04-01    2  236.49  452.17  -51.31  -164.38  06AEO-115
2     2024-04-01    3  221.27  273.51  -32.02   -20.22  06AEO-115
3     2024-04-01    4  209.96  266.56  -29.82   -26.78  06AEO-115
4     2024-04-01    5  209.89   263.4  -28.92   -24.58  06AEO-115
...          ...  ...     ...     ...     ...      ...        ...
1507  2024-04-07   20  466.18  968.62  -89.25  -413.19  06XOC-115
1508  2024-04-07   21  432.38  962.21  -92.75  -437.08  06XOC-115
1509  2024-04-07   22  327.86  962.91  -91.64  -543.41  06XOC-115
1510  2024-04-07   23   261.1  708.47  -66.56  -380.81  06XOC-115
1511  2024-04-07   24  225.22  412.64  -38.31  -149.12  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/04/08/2024/04/14/JSON
           fecha hora     pml pml_ene  pml_per  pml_cng       nodo
0     2024-04-08    1  411.94  748.04   -67.65  -268.45  06AEO-115
1     2024-04-08    2  256.23  315.26   -28.59   -30.44  06AEO-115
2     2024-04-08    3  231.44  252.71   -23.51     2.24  06AEO-115
3     2024-04-08    4  228.79  246.25   -23.87     6.41  06AEO-115
4     2024-04-08    5  225.01  246.45   -23.79     2.35  06AEO-115
...          ...  ...     ...     ...      ...      ...        ...
1507  2024-04-14   20  172.56  338.92   -39.36     -127  06XOC-115
1508  2024-04-14   21  179.07  601.32      -70  -352.26  06XOC-115
1509  2024-04-14   22  359.94  683.93   -77.41  -246.58  06XOC-115
1510  2024-04-14   23  436.96  895.79  -100.13   -358.7  06XOC-115
1511  2024-04-14   24  191.64  388.05   -45.06  -151.35  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/04/15/2024/04/21/JSON
           fecha hora     pml pml_ene  pml_per  pml_cng       nodo
0     2024-04-15    1  253.77     393   -43.97   -95.27  06AEO-115
1     2024-04-15    2     171  229.01   -26.35   -31.66  06AEO-115
2     2024-04-15    3  157.43  211.43   -24.89   -29.11  06AEO-115
3     2024-04-15    4  154.92  188.38   -22.01   -11.45  06AEO-115
4     2024-04-15    5  154.77  185.66   -21.59     -9.3  06AEO-115
...          ...  ...     ...     ...      ...      ...        ...
1507  2024-04-21   20  461.52  736.01   -83.78  -190.71  06XOC-115
1508  2024-04-21   21  481.94  845.44   -96.48  -267.02  06XOC-115
1509  2024-04-21   22  554.16   912.9  -103.16  -255.58  06XOC-115
1510  2024-04-21   23  351.44  708.93    -77.9  -279.59  06XOC-115
1511  2024-04-21   24     466  739.19   -79.12  -194.08  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/04/22/2024/04/28/JSON
           fecha hora      pml  pml_ene pml_per pml_cng       nodo
0     2024-04-22    1   245.02   283.95  -28.39  -10.54  06AEO-115
1     2024-04-22    2   226.28   264.32  -26.82  -11.22  06AEO-115
2     2024-04-22    3   220.89    257.6  -26.09  -10.63  06AEO-115
3     2024-04-22    4   216.99   252.14  -24.91  -10.24  06AEO-115
4     2024-04-22    5   216.66   250.61  -23.72  -10.23  06AEO-115
...          ...  ...      ...      ...     ...     ...        ...
1507  2024-04-28   20   750.46   856.29  -55.64  -50.19  06XOC-115
1508  2024-04-28   21  1170.09  1033.87  -59.41  195.64  06XOC-115
1509  2024-04-28   22  1005.63   887.17   -54.1  172.57  06XOC-115
1510  2024-04-28   23   1163.3  1027.38  -64.29  200.21  06XOC-115
1511  2024-04-28   24    607.7   662.29  -45.48   -9.12  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/04/29/2024/05/05/JSON
           fecha hora     pml  pml_ene  pml_per   pml_cng       nodo
0     2024-04-29    1  614.41   579.68   -33.87      68.6  06AEO-115
1     2024-04-29    2  340.48   331.13   -18.91     28.25  06AEO-115
2     2024-04-29    3  347.19   326.04   -19.68     40.83  06AEO-115
3     2024-04-29    4  315.98   291.51   -17.31     41.78  06AEO-115
4     2024-04-29    5  330.88   328.44    -19.2     21.65  06AEO-115
...          ...  ...     ...      ...      ...       ...        ...
1507  2024-05-05   20  556.35  1241.87  -116.19   -569.34  06XOC-115
1508  2024-05-05   21  789.73  3743.88  -342.08  -2612.07  06XOC-115
1509  2024-05-05   22  552.04  1226.09  -110.32   -563.73  06XOC-115
1510  2024-05-05   23   533.5  1062.08    -92.8   -435.78  06XOC-115
1511  2024-05-05   24   561.8   906.38   -77.65   -266.93  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/05/06/2024/05/12/JSON
           fecha hora     pml  pml_ene  pml_per   pml_cng       nodo
0     2024-05-06    1  715.49   932.17   -73.53   -143.15  06AEO-115
1     2024-05-06    2  355.88   488.96   -40.51    -92.57  06AEO-115
2     2024-05-06    3  449.14   438.64   -37.84     48.34  06AEO-115
3     2024-05-06    4  300.36      398   -34.36    -63.28  06AEO-115
4     2024-05-06    5  308.53   409.59   -35.02    -66.04  06AEO-115
...          ...  ...     ...      ...      ...       ...        ...
1507  2024-05-12   20  500.29  1975.43  -179.61  -1295.53  06XOC-115
1508  2024-05-12   21  539.85  1974.38  -175.75  -1258.78  06XOC-115
1509  2024-05-12   22  436.26  1075.25   -95.06   -543.94  06XOC-115
1510  2024-05-12   23  613.31   1100.7   -96.59    -390.8  06XOC-115
1511  2024-05-12   24  668.41    997.4   -88.63   -240.37  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/05/13/2024/05/19/JSON
           fecha hora      pml  pml_ene  pml_per   pml_cng       nodo
0     2024-05-13    1   496.13   577.39   -47.08    -34.19  06AEO-115
1     2024-05-13    2   414.13    483.1   -37.18    -31.79  06AEO-115
2     2024-05-13    3    378.6   404.68   -32.59      6.51  06AEO-115
3     2024-05-13    4    343.2   381.09   -30.83     -7.06  06AEO-115
4     2024-05-13    5   334.42   389.56   -31.74     -23.4  06AEO-115
...          ...  ...      ...      ...      ...       ...        ...
1507  2024-05-19   20   836.78  2509.48  -217.84  -1454.87  06XOC-115
1508  2024-05-19   21   742.14  2149.77  -181.89  -1225.74  06XOC-115
1509  2024-05-19   22   801.21  2286.82  -178.36  -1307.26  06XOC-115
1510  2024-05-19   23  1105.83  2003.43  -153.03   -744.56  06XOC-115
1511  2024-05-19   24  1601.89  2127.67  -171.26   -354.52  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/05/20/2024/05/26/JSON
           fecha hora      pml  pml_ene  pml_per pml_cng       nodo
0     2024-05-20    1  2215.26  2067.51  -124.84   272.6  06AEO-115
1     2024-05-20    2  1103.32  1089.98   -80.94   94.29  06AEO-115
2     2024-05-20    3   962.89  1001.92   -79.65   40.62  06AEO-115
3     2024-05-20    4   714.95   877.61   -72.46  -90.19  06AEO-115
4     2024-05-20    5   704.63      846   -69.36  -72.01  06AEO-115
...          ...  ...      ...      ...      ...     ...        ...
1507  2024-05-26   20  6341.33  6713.89  -324.68  -47.88  06XOC-115
1508  2024-05-26   21  8395.08  8701.43  -306.36       0  06XOC-115
1509  2024-05-26   22  8215.02   8480.3  -265.28       0  06XOC-115
1510  2024-05-26   23  8729.48  8797.84   -68.36       0  06XOC-115
1511  2024-05-26   24  3382.09  3506.06   -40.61  -83.36  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/05/27/2024/06/02/JSON
           fecha hora      pml  pml_ene pml_per pml_cng       nodo
0     2024-05-27    1  1923.58  2027.97  -60.35  -44.04  06AEO-115
1     2024-05-27    2  2554.34  2671.87  -95.25  -22.28  06AEO-115
2     2024-05-27    3  1770.17  1830.48  -96.26   35.96  06AEO-115
3     2024-05-27    4   894.23   914.67  -49.63   29.19  06AEO-115
4     2024-05-27    5   690.76   746.38  -41.61     -14  06AEO-115
...          ...  ...      ...      ...     ...     ...        ...
1507  2024-06-02   20    840.7   792.83  -58.67  106.53  06XOC-115
1508  2024-06-02   21   835.06   920.61  -61.01  -24.54  06XOC-115
1509  2024-06-02   22    840.6   919.81  -56.43  -22.78  06XOC-115
1510  2024-06-02   23  1002.17   1099.9  -57.96  -39.77  06XOC-115
1511  2024-06-02   24  1011.51  1085.22  -47.95  -25.76  06XOC-115

[1512 rows x 7 columns]
Datos para el request a 115/2024/06/03/2024/06/09/JSON
           fecha hora      pml  pml_ene  pml_per  pml_cng       nodo
0     2024-06-03    1   346.69   381.19   -21.14   -13.35  06AEO-115
1     2024-06-03    2   334.45   372.96   -24.43   -14.08  06AEO-115
2     2024-06-03    3   299.97   337.58   -23.13   -14.49  06AEO-115
3     2024-06-03    4   294.32   331.14   -24.45   -12.37  06AEO-115
4     2024-06-03    5   291.75   332.22    -26.4   -14.07  06AEO-115
...          ...  ...      ...      ...      ...      ...        ...
1507  2024-06-09   20  1475.35  2619.88  -200.66  -943.88  06XOC-115

In [ ]:
# dataframe consolidado
info = pd.concat(lista_chunks, ignore_index=True)

info.to_csv('monclova_pml_2024_2025.csv', index=False)

print(f"Filas totales recuperadas: {info.shape[0]}")
print(f"Columnas recuperadas: {info.shape[1]}")
info.head()

Filas totales recuperadas: 118152
Columnas recuperadas: 7

        fecha hora     pml pml_ene pml_per pml_cng       nodo
0  2024-01-01    1  279.92  370.71  -43.69   -47.1  06AEO-115
1  2024-01-01    2  279.21  311.75  -32.54       0  06AEO-115
2  2024-01-01    3  274.23  305.52  -31.28       0  06AEO-115
3  2024-01-01    4  264.01  294.23  -30.22       0  06AEO-115
4  2024-01-01    5  243.44  267.66  -24.22       0  06AEO-115

## Task 2: Modeling Tracks​